[package]
name = "jit-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = { version = "0.112.2", features = [
    "frontend",
    "jit",
    "module",
    "native",
], default-features = false }
